export const Product = [
  // ---------------------------------------------------------------- Men Clothing ----------------------------------------------------------------
  {
    id: 1,
    category: "Clothing",
    type: "Men",
    name: "Product-1",
    price: 19.99,
    image:
      "https://images.unsplash.com/photo-1505632958218-4f23394784a6?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 2,
    category: "Clothing",
    type: "Men",
    name: "Product-2",
    price: 29.99,
    image:
      "https://images.unsplash.com/photo-1559582798-678dfc71ccd8?crop=entropy&cs=tinysrgb&fit=max&ixid=MXwyMDg1NzN8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=400",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 3,
    category: "Clothing",
    type: "Men",
    name: "Product-3",
    price: 43.99,
    image:
      "https://d1fufvy4xao6k9.cloudfront.net/images/blog/posts/2024/07/hockerty_brown_cotton_polo_shirt_--ar_43_7910f81c-0c67-49c6-a350-b578061a1a81_1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 4,
    category: "Clothing",
    type: "Men",
    name: "Product-4",
    price: 269.99,
    image:
      "https://www.lashkaraa.com/cdn/shop/articles/jodhpuri-set.webp?v=1697536329&width=1100",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 5,
    category: "Clothing",
    type: "Men",
    name: "Product-5",
    price: 99.99,
    image:
      "https://www.libertyzeno.com/cdn/shop/articles/15-shoes-ideas-to-wear-with-white-pants-complete-guide-for-men-838189.jpg?v=1703407085",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 6,
    category: "Clothing",
    type: "Men",
    name: "Product-6",
    price: 49.99,
    image:
      "https://rukminim2.flixcart.com/image/850/1000/xif0q/sweatshirt/9/t/5/xl-nasavasasweat-eagle-america-original-imagmyckyafcrbtv.jpeg?q=90&crop=false",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 7,
    category: "Clothing",
    type: "Men",
    name: "Product-7",
    price: 124.99,
    image:
      "https://www.apetogentleman.com/wp-content/uploads/2020/08/8TypesOfShirtOwnMain.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 8,
    category: "Clothing",
    type: "Men",
    name: "Product-8",
    price: 21.99,
    image:
      "https://www.montecarlo.in/cdn/shop/products/2230101548-2-38_5.jpg?v=1700309816",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 9,
    category: "Clothing",
    type: "Men",
    name: "T-shirt",
    price: 139.99,
    image:
      "https://nobero.com/cdn/shop/files/WhatsAppImage2024-05-06at11.46.23AM.jpg?v=1723271991",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },
  {
    id: 10,
    category: "Clothing",
    type: "Men",
    name: "T-shirt",
    price: 82.99,
    image:
      "https://images.unsplash.com/photo-1484516396415-4971641de8e0?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmxhbmslMjB0JTIwc2hpcnR8ZW58MHx8MHx8fDA%3D",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 10,
  },

  // ---------------------------------------------------------------- Women Clothing ----------------------------------------------------------------

  {
    id: 1,
    category: "Clothing",
    type: "Women",
    name: "Product-1",
    price: 59.99,
    image:
      "https://img.freepik.com/free-photo/medium-shot-cute-girl-tokyo_23-2148665357.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 5,
    reviews: 15,
  },
  {
    id: 2,
    category: "Clothing",
    type: "Women",
    name: "Product-2",
    price: 19.99,
    image:
      "https://img.freepik.com/free-photo/elegant-young-woman-dress-with-crossed-hands-handbag-room_23-2148068409.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 3,
    reviews: 11,
  },
  {
    id: 3,
    category: "Clothing",
    type: "Women",
    name: "Product-3",
    price: 88.99,
    image:
      "https://img.freepik.com/free-photo/young-indian-woman-wearing-sari_23-2149400867.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4,
    reviews: 40,
  },
  {
    id: 4,
    category: "Clothing",
    type: "Women",
    name: "Product-4",
    price: 29.99,
    size: "large",
    image:
      "https://img.perniaspopupshop.com/HOMEPAGE_IMAGES/WOMEN/01_Nov_24/Diyarajvvir_WT_1_11_24.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4,
    reviews: 21,
  },
  {
    id: 5,
    category: "Clothing",
    type: "Women",
    name: "Product-5",
    price: 95.99,
    image:
      "https://images.unsplash.com/photo-1642597611045-7bd6e09c4d2e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nzl8fGNsb3RoaW5nJTIwc3RvcmV8ZW58MHx8MHx8fDA%3D  ",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 5,
    reviews: 19,
  },
  {
    id: 6,
    category: "Clothing",
    type: "Women",
    name: "Product-6",
    price: 114.99,
    image:
      "https://images.unsplash.com/photo-1615125990940-590bb28a2cea?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d29tZW4lMjBjbG90aGVzJTIwJTIwcGhvdG9ncmFwaHl8ZW58MHwwfDB8fHww",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 2,
    reviews: 41,
  },
  {
    id: 7,
    category: "Clothing",
    type: "Women",
    name: "Product-7",
    price: 64.99,
    image:
      "https://sassafras.in/cdn/shop/products/SFSWSH7464-5_1800x.jpg?v=1700582719",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 8,
    category: "Clothing",
    type: "Women",
    name: "Product-8",
    price: 79.99,
    image:
      "https://thevishnu.in/cdn/shop/articles/blog1_vishnu_900x.png?v=1718008804",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 3,
    reviews: 80,
  },

  {
    id: 9,
    category: "Clothing",
    type: "Women",
    name: "Product-9",
    price: 49.99,
    image:
      "https://cdn.shopify.com/s/files/1/0582/2270/6885/files/2_1ebdbb00-7c59-4a6d-ada0-54b29b15dea3.jpg?v=1632141942",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4,
    reviews: 8,
  },

  {
    id: 10,
    category: "Clothing",
    type: "Women",
    name: "Product-10",
    price: 129.99,
    image:
      "https://www.instyle.com/thmb/2vTd6ZZW5hRCu8Xv5-JxC_tvSWk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-2153285641-0a7d20bfbe7949a4bfea27ad075d175f.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 1,
    reviews: 1,
  },

  // --------------------------------------------------------------- Shoes ---------------------------------------------------------------

  {
    id: 1,
    category: "Shoes",
    type: "Running",
    name: "Classic Running Shoes",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    alt: "Classic white and red running shoes",
  },
  {
    id: 2,
    category: "Shoes",
    type: "Running",
    name: "Urban Sneakers",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    alt: "Modern urban style sneakers",
  },
  {
    id: 3,
    category: "Shoes",
    type: "Running",
    name: "Sport Elite",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570",
    alt: "Premium sports running shoes",
  },
  {
    id: 4,
    category: "Shoes",
    type: "Running",
    name: "Comfort Walker",
    price: 99.99,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    alt: "Comfortable walking shoes",
  },
  {
    id: 5,
    category: "Shoes",
    type: "Running",
    name: "Trail Runner Pro",
    price: 159.99,
    image: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2",
    alt: "Professional trail running shoes",
  },
  {
    id: 6,
    category: "Shoes",
    type: "Running",
    name: "Lifestyle Series",
    price: 139.99,
    image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    alt: "Casual lifestyle sneakers",
  },

  // ----------------------------------------------------------------- Electronics -----------------------------------------------------------------

  {
    id: 1,
    category: "Electronics",
    type: "Tech",
    name: "Premium Wireless Headphones",
    price: 299.99,
    description: "High-quality wireless headphones with noise cancellation",
    image: "images.unsplash.com/photo-1505740420928-5e560c06d30e",
    stock: 10,
    rating: 4.5
  },
  {
    id: 2,
    category: "Electronics",
    type: "Tech",
    name: "4K Smart TV",
    price: 799.99,
    description: "55-inch 4K Ultra HD Smart LED TV with HDR",
    image: "images.unsplash.com/photo-1593359677879-a4bb92f829d1",
    stock: 5,
    rating: 4.8
  },
  {
    id: 3,
    category: "Electronics",
    type: "Tech",
    name: "Professional Camera",
    price: 1299.99,
    description: "24.2MP Digital SLR Camera with 18-55mm Lens",
    image: "images.unsplash.com/photo-1516035069371-29a1b244cc32",
    stock: 3,
    rating: 4.7
  },
  {
    id: 3,
    category: "Electronics",
    type: "Tech",
    name: "Professional Camera",
    price: 1299.99,
    description: "24.2MP Digital SLR Camera with 18-55mm Lens",
    image: "images.unsplash.com/photo-1516035069371-29a1b244cc32",
    stock: 3,
    rating: 4.7
  },
  {
    id: 3,
    category: "Electronics",
    type: "Tech",
    name: "Professional Camera",
    price: 1299.99,
    description: "24.2MP Digital SLR Camera with 18-55mm Lens",
    image: "images.unsplash.com/photo-1516035069371-29a1b244cc32",
    stock: 3,
    rating: 4.7
  },
  {
    id: 3,
    category: "Electronics",
    type: "Tech",
    name: "Professional Camera",
    price: 1299.99,
    description: "24.2MP Digital SLR Camera with 18-55mm Lens",
    image: "images.unsplash.com/photo-1516035069371-29a1b244cc32",
    stock: 3,
    rating: 4.7
  },

  //--------------------------------------------------------------------- HOME DECOR ---------------------------------------------------------------------

    {
      id: 1,
      name: "Modern Table Lamp",
      category: "HomeDecor",
      type:"Decor",
      price: 129.99,
      description: "Elegant table lamp with adjustable brightness",
      image: "images.unsplash.com/photo-1513506003901-1e6a229e2d15",
      popularity: 4.5
    },
    {
      id: 2,
      name: "Velvet Accent Chair",
      category: "HomeDecor",
      type:"Decor",
      price: 299.99,
      description: "Comfortable accent chair with premium velvet upholstery",
      image: "images.unsplash.com/photo-1567538096630-e0c55bd6374c",
      popularity: 4.8
    },
    {
      id: 3,
      name: "Decorative Wall Mirror",
      category: "HomeDecor",
      type:"Decor",
      price: 89.99,
      description: "Round wall mirror with golden frame",
      image: "images.unsplash.com/photo-1507926672279-3ff06c0b6280",
      popularity: 4.2
    },
    {
      id: 4,
      name: "Pendant Light Fixture",
      category: "HomeDecor",
      type:"Decor",
      price: 159.99,
      description: "Modern pendant light with metal finish",
      image: "images.unsplash.com/photo-1524484485831-a92ffc0de03f",
      popularity: 4.6
    },
    {
      id: 5,
      name: "Leather Sofa",
      category: "HomeDecor",
      type:"Decor",
      price: 899.99,
      description: "Premium leather sofa with modern design",
      image: "images.unsplash.com/photo-1555041469-a586c61ea9bc",
      popularity: 4.9
    },
    {
      id: 6,
      name: "Ceramic Vase Set",
      category: "HomeDecor",
      type:"Decor",
      price: 79.99,
      description: "Set of 3 decorative ceramic vases",
      image: "images.unsplash.com/photo-1578500494198-246f612d3b3d",
      popularity: 4.3
    },
    {
      id: 7,
      name: "Floor Lamp",
      category: "HomeDecor",
      type:"Decor",
      price: 199.99,
      description: "Contemporary floor lamp with reading light",
      image: "images.unsplash.com/photo-1507473885765-e6ed057f782c",
      popularity: 4.7
    },
    {
      id: 8,
      name: "Dining Table Set",
      category: "HomeDecor",
      type:"Decor",
      price: 699.99,
      description: "Modern dining table with 6 chairs",
      image: "images.unsplash.com/photo-1617806118233-18e1de247200",
      popularity: 4.8
    },
    {
      id: 9,
      name: "Wall Clock",
      category: "HomeDecor",
      type:"Decor",
      price: 49.99,
      description: "Minimalist wall clock with wooden frame",
      image: "images.unsplash.com/photo-1563861826100-9cb868fdbe1c",
      popularity: 4.4
    },
    {
      id: 10,
      name: "Crystal Chandelier",
      category: "HomeDecor",
      type:"Decor",
      price: 459.99,
      description: "Luxurious crystal chandelier for dining room",
      image: "images.unsplash.com/photo-1519710164239-da123dc03ef4",
      popularity: 4.9
    },

    //--------------------------------------------------------------------- HOME APPLIANCES ---------------------------------------------------------------------

   { id: 1,
    name: "Crystal Chandelier",
    category: "HomeAppliances",
    type: "Appliances",
    price: 459.99,
    description: "Elegant crystal chandelier to illuminate your space.",
    image: "img.freepik.com/free-photo/contemporary-chandelier_1385-2783.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    popularity: 4.9,
  },
  {
    id: 2,
    name: "Samsung Refrigerator",
    category: "HomeAppliances",
    type: "Appliances",
    price: 799.99,
    description: "Spacious fridge with advanced cooling technology.",
    image: "img.freepik.com/free-vector/opened-wider-empty-refrigerator_1284-23309.jpg?t=st=1731690723~exp=1731694323~hmac=2ffedf0e23a4ff47b4d3228fa00caea5a5cef63baad474b28deb4ffdf3f06b5e&w=740",
    popularity: 4.8,
  },
  {
    id: 3,
    name: "LG Washing Machine",
    category: "HomeAppliances",
    type: "Appliances",
    price: 599.99,
    description: "High-efficiency washing machine with smart features.",
    image: "img.freepik.com/free-vector/washing-machine-realistic-poster-with-quiet-quick-wash-symbols-illustration_1284-29131.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    popularity: 4.7,
  },
  {
    id: 4,
    name: "Microwave Oven",
    category: "HomeAppliances",
    type: "Appliances",
    price: 249.99,
    description: "Compact oven for efficient cooking and reheating.",
    image: "img.freepik.com/free-vector/microwave-oven-with-light-inside-isolated-white-background-kitchen-appliances_134830-658.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    popularity: 4.6,
  },
  {
    id: 5,
    name: "Water Purifier",
    category: "HomeAppliances",
    type: "Appliances",
    price: 199.99,
    description: "Advanced purifier for clean and safe drinking water.",
    image: "cdn-jmlld.nitrocdn.com/qydppaFNcKMRjVLinmLFvQMpPBYfFFCk/assets/images/optimized/rev-465a996/www.aosmithindia.com/wp-content/themes/aosmith/assets/images/water_purification.jpg",
    popularity: 4.8,
  },
  {
    id: 6,
    name: "Non-Stick Dosa Pan",
    category: "HomeAppliances",
    type: "Appliances",
    price: 29.99,
    description: "Durable non-stick pan for perfect dosas every time.",
    image: "www.potsandpans.in/cdn/shop/products/Edgeless_Tawa_1_900x.jpg?v=1572514225",
    popularity: 4.5,
  },
  {
    id: 7,
    name: "Mixer Grinder",
    category: "HomeAppliances",
    type: "Appliances",
    price: 89.99,
    description: "Versatile mixer grinder for your everyday kitchen needs.",
    image: "shop.kamalastores.com/cdn/shop/products/81AKlOUHvq3L_1024x1024@2x.png?v=1633184935",
    popularity: 4.7,
  },
  {
    id: 8,
    name: "Wet Grinder",
    category: "HomeAppliances",
    type: "Appliances",
    price: 129.99,
    description: "Efficient grinder for smooth batters and pastes.",
    image: "https://source.unsplash.com/400x400/?wet-grinder",
    popularity: 4.6,
  },
  {
    id: 9,
    name: "Kitchen Utensils Set",
    category: "HomeAppliances",
    type: "Appliances",
    price: 59.99,
    description: "Complete set of utensils for a modern kitchen.",
    image: "https://source.unsplash.com/400x400/?kitchen-utensils",
    popularity: 4.9,
  },
  {
    id: 10,
    name: "Gas Stove",
    category: "HomeAppliances",
    type: "Appliances",
    price: 159.99,
    description: "Durable and efficient gas stove for your cooking needs.",
    image: "https://source.unsplash.com/400x400/?gas-stove",
    popularity: 4.8,
  },

  //--------------------------------------------------------------------- TOYS ---------------------------------------------------------------------
    {
      id: 1,
      name: "Toy Story Set",
      category: "Toys",
      type: "All",
      price: 159.99,
      description: "A complete set of Toy Story characters for kids.",
      image: "encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRWg9L8BhasUi4nJyVGNRRifx4QaE--E5F22jCySl5JtWQEv0_6gb_uwfni3sV9_SyzC3Xk1LqKH28l8Edmgiv6YHhXcTjyH33ZyBDAP2v5AYahm2bi0pxM&usqp=CAE",
      popularity: 4.8,
    },
    {
      id: 2,
      name: "Lego AMG and G-Wagon",
      category: "Toys",
      type: "All",
      price: 99.99,
      description: "Creative Lego blocks for AMG and G-wagon play.",
      image: "encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ11zX7x7rHahljN__cu8AG2_6A4_rIhYPCYQWYX2nFmHlD_wcTDUAo_9eV_NpsdQAZbjR0nEsbKtw-Flrb9iPZPjR0H8rbBw1GYqUnFt8G&usqp=CAE",
      popularity: 4.9,
    },
    {
      id: 3,
      name: "Remote Control Car",
      category: "Toys",
      type: "All",
      price: 49.99,
      description: "High-speed remote control car with rechargeable battery.",
      image: "img.freepik.com/premium-photo/remote-control-car-with-rechargeable-battery_872941-2220.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      popularity: 4.7,
    },
    {
      id: 4,
      name: "Barbie Dollhouse",
      category: "Toys",
      type: "All",
      price: 129.99,
      description: "A luxurious dollhouse with furniture for Barbie dolls.",
      image: "encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQS-juHGNXnlA_vUVqCnQ9McttfAZTGX6mDRAR3bmnVRh2VtcGxpbK7gkhVHr0s5lcgTVoVsk4VtZPkfYCtyMETlFRI_uyfJt0L75Duv0mT&usqp=CAE",
      popularity: 4.8,
    },
    {
      id: 5,
      name: "Stuffed Teddy Bear",
      category: "Toys",
      type: "All",
      price: 29.99,
      description: "Soft and cuddly teddy bear for endless hugs.",
      image: "img.freepik.com/free-photo/cute-teddy-bear-indoors-still-life_23-2151083636.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      popularity: 4.9,
    },
    {
      id: 6,
      name: "Puzzle Set",
      category: "Toys",
      type: "All",
      price: 19.99,
      description: "Engaging puzzle set to challenge young minds.",
      image: "rukminim2.flixcart.com/image/720/864/kst9gnk0/role-play-toy/q/n/i/kids-number-puzzles-mini-size-play-puzzle-numbers-set-toy-kids-original-imag6bfkdjhyh9wx.jpeg?q=60&crop=false",
      popularity: 4.6,
    },
    {
      id: 7,
      name: "Rubik's original",
      category: "Toys",
      type: "All",
      price: 49.99,
      description: "A Puzzle cube of 3x3 side ",
      image: "//rukminim2.flixcart.com/image/850/1000/kpft18w0/puzzle/o/m/k/1-high-speed-rubik-s-cube-smooth-magic-puzzle-cube-brainteaser-original-imag3zmgzfawsvj8.jpeg?q=90&crop=false",
      popularity: 4.7,
    },
    {
      id: 8,
      name: "Play Kitchen Set",
      category: "Toys",
      type: "All",
      price: 79.99,
      description: "Miniature kitchen set for fun cooking role-play.",
      image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTYEc4R0IQgPoZNw8Xg7sS-h6_DaQpdFWIMOWUuOS9SsKgRl2NvkPpEmgCNPytICzcCezbyi8BijxGSOachzQmF7acOOVjlA3RXfxWuv81lbN7VFvW5vziZ&usqp=CAE",
      popularity: 4.8,
    },
    {
      id: 9,
      name: "Toy Train Set",
      category: "Toys",
      type: "All",
      price: 89.99,
      description: "Electric toy train set with tracks and accessories.",
      image: "encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQV5IiBaZ6-H55zK08KsdNvVYnWv_ca-0Ap1zOx-IVRwfrxrXXjOiXeUo1jlahZ2CMiyYIdQHQIhTMYiFr-jXEqxWbvW994QyxKXMJzK3US4E8UEDQ6NMsD&usqp=CAE",
      popularity: 4.6,
    },
    {
      id: 10,
      name: "Kids' Art Supplies",
      category: "Toys",
      type: "All",
      price: 39.99,
      description: "Complete set of art supplies to inspire creativity.",
      image: "encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSqaChfZ-_Z6Bf5_F9_l5yBGsP0OHNzvpChj4clsiWTo2EIRcGlH9VR7EggEanCUlAgPZ3Bw-ucWF36HdSMb-fpNth4rHeaTEpPWLKleSw&usqp=CAE",
      popularity: 4.7,
    },
  
// -------------------------------------------------------------- COSMETICS ----------------------------------------------------------------------------------------------

      {
        id: 1,
        name: "Matte Lipstick Set",
        category: "Cosmetics",
        type: "All",
        price: 29.99,
        description: "Long-lasting matte lipstick set with vibrant colors.",
        image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTqm_mGWcT-lgHR86j6szNjlXeCjsUwvLF3eOGPzm8isISFS0vWZXEo7s0RVOVlOF7KekhxeywokyxusVmt_7qb2oVNnQrt_1KLrx03iXECGZbOaewFlnfP&usqp=CAE",
        popularity: 4.8,
      },
      {
        id: 2,
        name: "Hydrating Face Cream",
        category: "Cosmetics",
        type: "All",
        price: 24.99,
        description: "Deeply moisturizing face cream for glowing skin.",
        image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRC1hkoxDFBk22tDIlAcXsXhNO4pg959h6goDK0xJ9S5I-jR6ooKp2R2MMzHBf4PZUOJeKe_76SvcWppuj_d54yzEOdugxpjoZKSiFrbo1H&usqp=CAE",
        popularity: 4.7,
      },
      {
        id: 3,
        name: "Waterproof Mascara",
        category: "Cosmetics",
        type: "All",
        price: 19.99,
        description: "Smudge-proof and waterproof mascara for dramatic lashes.",
        image: "encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSZ4bMNVLe6hqr4yulUVpavG2vKTLxWlruHhtgTqgy6CphqhAO5rFLNDwahMxtqmYmLV-v9EjuQl3V92jxoakCEshlE47IhOXbgEnACou8cpQ7iHzQNX693&usqp=CAE",
        popularity: 4.9,
      },
      {
        id: 4,
        name: "Vitamin C Serum",
        category: "Cosmetics",
        type: "All",
        price: 39.99,
        description: "Brightening serum with vitamin C and hyaluronic acid.",
        image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR0r3GteRu6ds8deytla3wkbtKeHQR2hzhcMj1xgM_quCZa0wrhJqMuo8NR6bc4dQUv0SULWO7TBWwhI6oO1Z4oDt9VRJq07C5SD1WwrHlbjo0EeYSz94-Z-w&usqp=CAE",
        popularity: 4.8,
      },
      {
        id: 5,
        name: "Eyeshadow Palette",
        category: "Cosmetics",
        type: "All",
        price: 49.99,
        description: "Palette with 16 pigmented shades for every occasion.",
        image: "encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSPjm8zxOtGUzAknJbmzXplsJBPJx4ens_EEeQBTtSkNESxxBlfpTFDKGI1HJ-g-RU4jKONkwF_RUzWIdQp_tc2IAeBr6RwQYM4h_mg2JppAUy67HrqutL7&usqp=CAE",
        popularity: 4.6,
      },
      {
        id: 6,
        name: "Nail Polish Set",
        category: "Cosmetics",
        type: "All",
        price: 15.99,
        description: "Collection of quick-drying nail polishes in trendy colors.",
        image: "encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQSWv1Ac9HUE908Hh24jpdTTwXabziaN717Dc254PEUszJYWk7sFu73T_P0xDrzI6Rww_jvZaCSvg4WwvCsFb7jxpaH5SWVQl19GB3tbMzdReg8X_Kri465&usqp=CAE",
        popularity: 4.7,
      },
      {
        id: 7,
        name: "Liquid Foundation",
        category: "Cosmetics",
        type: "All",
        price: 34.99,
        description: "Lightweight foundation for a flawless base.",
        image: "encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQsvpi9ERCVnucmhXN4MksKg-TDesznPFW1zfE8NUTERu5j_5irTMbsgvExc9juDoqCuAVJVIWJkuTA0T3Ld89vP0Jf7wmQViEQ2BINUaqbMuElNSTmUXhmh58&usqp=CAE",
        popularity: 4.8,
      },
      {
        id: 8,
        name: "Charcoal Face Mask",
        category: "Cosmetics",
        type: "All",
        price: 19.99,
        description: "Detoxifying face mask with activated charcoal.",
        image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS1wMjupLtcwJhiFnRXB-aPWYtE7UVWl1MACkM44Yu4FNPPx_P-HUpsK8UM70Veu3ZnDZIbssaYyFTkCCLdaQ_FaQqNc1bEd3kc80XtP8wNEEouIsTIxtxN&usqp=CAE",
        popularity: 4.5,
      },
      {
        id: 9,
        name: "Makeup Brushes Set",
        category: "Cosmetics",
        type: "All",
        price: 29.99,
        description: "Professional brush set for seamless makeup application.",
        image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTrxu7iJnzpbX1JxzK5zb3LMHzeXro8R2E6-626KQ2izboch2hRoNouSn8smXAh2JvGpEbh8W_Kd7eS4VkfZFa_3f1to-wGXPK7kO7uD1avv8YPxMqY_uMU&usqp=CAE",
        popularity: 4.9,
      },
      {
        id: 10,
        name: "Sunscreen SPF 50",
        category: "Cosmetics",
        type: "All",
        price: 25.99,
        description: "Broad-spectrum sunscreen with SPF 50 for sun protection.",
        image: "encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSIN90_RNvojoQAm3EHsCA7djizl6T3U5DWs9UlWn1E-rLdqBxXlUg0fokSPtUKjmU_TkD76AKXp5fec6AjwAt5LEr19HJbi-HDUrAmmmbmfMCzu26hBiIX&usqp=CAE",
        popularity: 4.8,
      },
    
// -------------------------------------------------------------- TOOLS AND EQUIPMENTS ------------------------------------------------------------------------------------------------


{
  id: 1,
  name: "Cordless Drill",
  category: "Tools",
  type: "Equipments",
  price: 89.99,
  description: "High-performance cordless drill with rechargeable battery.",
  image: "https://source.unsplash.com/400x400/?cordless-drill",
  popularity: 4.8,
},

  {
    id: 2,
    name: "Adjustable Wrench",
   category: "Tools",
  type: "Equipments",
    price: 14.99,
    description: "Durable adjustable wrench for various bolt sizes.",
    image: "https://source.unsplash.com/400x400/?wrench",
    popularity: 4.7,
  },
  {
    id: 3,
    name: "Circular Saw",
   category: "Tools",
  type: "Equipments",
    price: 129.99,
    description: "Efficient circular saw for precise wood and metal cutting.",
    image: "https://source.unsplash.com/400x400/?circular-saw",
    popularity: 4.8,
  },
  {
    id: 4,
    name: "Tape Measure",
   category: "Tools",
  type: "Equipments",
    price: 9.99,
    description: "Retractable tape measure with a 25-foot reach.",
    image: "https://source.unsplash.com/400x400/?tape-measure",
    popularity: 4.6,
  },
  {
    id: 5,
    name: "Multi-Bit Screwdriver",
   category: "Tools",
  type: "Equipments",
    price: 19.99,
    description: "Ergonomic screwdriver with interchangeable bits.",
    image: "https://source.unsplash.com/400x400/?screwdriver",
    popularity: 4.7,
  },
  {
    id: 6,
    name: "Toolbox Organizer",
   category: "Tools",
  type: "Equipments",
    price: 34.99,
    description: "Compact toolbox for organizing and storing tools.",
    image: "https://source.unsplash.com/400x400/?toolbox",
    popularity: 4.9,
  },
  {
    id: 7,
    name: "Electric Sander",
   category: "Tools",
  type: "Equipments",
    price: 49.99,
    description: "Smooth finish electric sander for woodworking projects.",
    image: "https://source.unsplash.com/400x400/?electric-sander",
    popularity: 4.5,
  },
  {
    id: 8,
    name: "Hammer",
   category: "Tools",
  type: "Equipments",
    price: 12.99,
    description: "Heavy-duty hammer for construction and DIY tasks.",
    image: "https://source.unsplash.com/400x400/?hammer",
    popularity: 4.7,
  },
  {
    id: 9,
    name: "Work Gloves",
   category: "Tools",
  type: "Equipments",
    price: 9.99,
    description: "Durable and comfortable gloves for protection.",
    image: "https://source.unsplash.com/400x400/?work-gloves",
    popularity: 4.8,
  },
  {
    id: 10,
    name: "Ladder",
   category: "Tools",
  type: "Equipments",
    price: 74.99,
    description: "Sturdy folding ladder for household and professional use.",
    image: "https://source.unsplash.com/400x400/?ladder",
    popularity: 4.6,
  },




// ----------------------------------------------------------------- STATIONERY ITEMS -------------------------------------------------------------------------------




  {
    id: 1,
    name: "Classic Ballpoint Pens",
    category: "Stationery",
    type: "All",
    price: 5.99,
    description: "A set of 10 smooth and reliable ballpoint pens.",
    image: "https://source.unsplash.com/400x400/?pen",
    popularity: 4.8,
  },
  {
    id: 2,
    name: "Hardcover Notebook",
   category: "Stationery",
    type: "All",
    price: 9.99,
    description: "Durable notebook with ruled pages, perfect for journaling.",
    image: "https://source.unsplash.com/400x400/?notebook",
    popularity: 4.7,
  },
  {
    id: 3,
    name: "Colorful Sticky Notes",
   category: "Stationery",
    type: "All",
    price: 4.99,
    description: "Bright and colorful sticky notes for reminders and bookmarks.",
    image: "https://source.unsplash.com/400x400/?sticky-notes",
    popularity: 4.6,
  },
  {
    id: 4,
    name: "Mechanical Pencils Set",
   category: "Stationery",
    type: "All",
    price: 7.99,
    description: "Pack of 5 refillable mechanical pencils with 0.5mm leads.",
    image: "https://source.unsplash.com/400x400/?pencil",
    popularity: 4.7,
  },
  {
    id: 5,
    name: "Highlighter Pack",
   category: "Stationery",
    type: "All",
    price: 6.99,
    description: "Set of 6 fluorescent highlighters for study and office work.",
    image: "https://source.unsplash.com/400x400/?highlighter",
    popularity: 4.9,
  },
  {
    id: 6,
    name: "Desk Organizer",
  category: "Stationery",
    type: "All",
    price: 12.99,
    description: "Compact desk organizer with multiple compartments for tools.",
    image: "https://source.unsplash.com/400x400/?desk-organizer",
    popularity: 4.8,
  },
  {
    id: 7,
    name: "Erasable Gel Pens",
   category: "Stationery",
    type: "All",
    price: 8.99,
    description: "Set of 3 gel pens with erasable ink for mistake-free writing.",
    image: "https://source.unsplash.com/400x400/?erasable-pen",
    popularity: 4.6,
  },
  {
    id: 8,
    name: "Stapler with Staples",
   category: "Stationery",
    type: "All",
    price: 6.49,
    description: "Compact stapler with 500 staples included for easy use.",
    image: "https://source.unsplash.com/400x400/?stapler",
    popularity: 4.7,
  },
  {
    id: 9,
    name: "Ruler and Protractor Set",
   category: "Stationery",
    type: "All",
    price: 3.99,
    description: "Essential tools for precision and geometry tasks.",
    image: "https://source.unsplash.com/400x400/?ruler",
    popularity: 4.6,
  },
  {
    id: 10,
    name: "Artistic Sketch Pad",
   category: "Stationery",
    type: "All",
    price: 14.99,
    description: "High-quality sketch pad with textured pages for drawing.",
    image: "https://source.unsplash.com/400x400/?sketchbook",
    popularity: 4.9,
  },






// ----------------------------------------------------------------- BOOKS -------------------------------------------------------------------------------

  {
    id: 1,
    name: "The Great Gatsby",
    category: "Books",
    type: "All",
    price: 14.99,
    description: "A classic novel by F. Scott Fitzgerald exploring themes of wealth and ambition.",
    image: "https://source.unsplash.com/400x400/?book",
    popularity: 4.9,
  },
  {
    id: 2,
    name: "Sapiens: A Brief History of Humankind",
    category: "Books",
    type: "All",
    price: 19.99,
    description: "Yuval Noah Harari's exploration of humanity's history and evolution.",
    image: "https://source.unsplash.com/400x400/?non-fiction-book",
    popularity: 4.8,
  },
  {
    id: 3,
    name: "The Catcher in the Rye",
    category: "Books",
    type: "All",
    price: 12.99,
    description: "J.D. Salinger's iconic story of teenage rebellion and identity.",
    image: "https://source.unsplash.com/400x400/?novel",
    popularity: 4.7,
  },
  {
    id: 4,
    name: "Atomic Habits",
    category: "Books",
    type: "All",
    price: 16.99,
    description: "James Clear's guide to building good habits and breaking bad ones.",
    image: "https://source.unsplash.com/400x400/?self-help-book",
    popularity: 4.8,
  },
  {
    id: 5,
    name: "1984",
    category: "Books",
    type: "All",
    price: 15.99,
    description: "George Orwell's dystopian novel about a totalitarian society.",
    image: "https://source.unsplash.com/400x400/?1984-book",
    popularity: 4.9,
  },
  {
    id: 6,
    name: "Becoming",
    category: "Books",
    type: "All",
    price: 18.99,
    description: "Michelle Obama's inspiring memoir about her life and career.",
    image: "https://source.unsplash.com/400x400/?biography-book",
    popularity: 4.8,
  },
  {
    id: 7,
    name: "The Alchemist",
   category: "Books",
    type: "All",
    price: 13.99,
    description: "Paulo Coelho's tale of self-discovery and pursuing one's dreams.",
    image: "https://source.unsplash.com/400x400/?fiction-book",
    popularity: 4.7,
  },
  {
    id: 8,
    name: "Educated",
    category: "Books",
    type: "All",
    price: 17.99,
    description: "Tara Westover's memoir of overcoming a challenging childhood through education.",
    image: "https://source.unsplash.com/400x400/?memoir-book",
    popularity: 4.9,
  },
  {
    id: 9,
    name: "Harry Potter and the Sorcerer's Stone",
    category: "Books",
    type: "All",
    price: 20.99,
    description: "J.K. Rowling's magical story of Harry Potter's first year at Hogwarts.",
    image: "https://source.unsplash.com/400x400/?fantasy-book",
    popularity: 4.9,
  },
  {
    id: 10,
    name: "The Subtle Art of Not Giving a F*ck",
    category: "Books",
    type: "All",
    price: 15.99,
    description: "Mark Manson's counterintuitive approach to living a good life.",
    image: "https://source.unsplash.com/400x400/?motivational-book",
    popularity: 4.6,
  },


  



];
