export const Product = [
  // ---------------------------------------------------------------- Men Clothing ----------------------------------------------------------------
  
    {
      id: 1,
      category: "Clothing",
      type: "Men",
      name: "Product-1",
      price: 23.99, 
      disprice: 19.99, 
      image: "https://images.unsplash.com/photo-1505632958218-4f23394784a6?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
      stock: 1
    },
    {
      id: 2,
      category: "Clothing",
      type: "Men",
      name: "Product-2",
      price: 35.99,
      disprice: 29.99,
      image: "https://images.unsplash.com/photo-1559582798-678dfc71ccd8?crop=entropy&cs=tinysrgb&fit=max&ixid=MXwyMDg1NzN8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=400",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 20,
    },
    {
      id: 3,
      category: "Clothing",
      type: "Men",
      name: "Product-3",
      price: 52.79,
      disprice: 43.99,
      image: "https://d1fufvy4xao6k9.cloudfront.net/images/blog/posts/2024/07/hockerty_brown_cotton_polo_shirt_--ar_43_7910f81c-0c67-49c6-a350-b578061a1a81_1.jpg",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 4,
      category: "Clothing",
      type: "Men",
      name: "Product-4",
      price: 323.99,
      disprice: 269.99,
      image: "https://www.lashkaraa.com/cdn/shop/articles/jodhpuri-set.webp?v=1697536329&width=1100",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 5,
      category: "Clothing",
      type: "Men",
      name: "Product-5",
      price: 119.99,
      disprice: 99.99,
      image: "https://www.libertyzeno.com/cdn/shop/articles/15-shoes-ideas-to-wear-with-white-pants-complete-guide-for-men-838189.jpg?v=1703407085",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 6,
      category: "Clothing",
      type: "Men",
      name: "Product-6",
      price: 59.99,
      disprice: 49.99,
      image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/sweatshirt/9/t/5/xl-nasavasasweat-eagle-america-original-imagmyckyafcrbtv.jpeg?q=90&crop=false",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 7,
      category: "Clothing",
      type: "Men",
      name: "Product-7",
      price: 149.99,
      disprice: 124.99,
      image: "https://www.apetogentleman.com/wp-content/uploads/2020/08/8TypesOfShirtOwnMain.jpg",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 8,
      category: "Clothing",
      type: "Men",
      name: "Product-8",
      price: 26.39,
      disprice: 21.99,
      image: "https://www.montecarlo.in/cdn/shop/products/2230101548-2-38_5.jpg?v=1700309816",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 9,
      category: "Clothing",
      type: "Men",
      name: "T-shirt",
      price: 167.99,
      disprice: 139.99,
      image: "https://nobero.com/cdn/shop/files/WhatsAppImage2024-05-06at11.46.23AM.jpg?v=1723271991",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 10,
      category: "Clothing",
      type: "Men",
      name: "T-shirt",
      price: 99.59,
      disprice: 82.99,
      image: "https://images.unsplash.com/photo-1484516396415-4971641de8e0?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmxhbmslMjB0JTIwc2hpcnR8ZW58MHx8MHx8fDA%3D",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
  
    // ---------------------------------------------------------------- Women Clothing ----------------------------------------------------------------
  
    {
      id: 1,
      category: "Clothing",
      type: "Women",
      name: "Product-1",
      price: 71.99,
      disprice: 59.99,
      image: "https://img.freepik.com/free-photo/medium-shot-cute-girl-tokyo_23-2148665357.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 5,
      reviews: 15,
    },
    {
      id: 2,
      category: "Clothing",
      type: "Women",
      name: "Product-2",
      price: 23.99,
      disprice: 19.99,
      image: "https://img.freepik.com/free-photo/elegant-young-woman-dress-with-crossed-hands-handbag-room_23-2148068409.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 3,
      reviews: 11,
    },
    {
      id: 3,
      category: "Clothing",
      type: "Women",
      name: "Product-3",
      price: 106.79,
      disprice: 88.99,
      image: "https://img.freepik.com/free-photo/young-indian-woman-wearing-sari_23-2149400867.jpg",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4,
      reviews: 40,
    },
    {
      id: 4,
      category: "Clothing",
      type: "Women",
      name: "Product-4",
      price: 35.99,
      disprice: 29.99,
      size: "large",
      image: "https://img.perniaspopupshop.com/HOMEPAGE_IMAGES/WOMEN/01_Nov_24/Diyarajvvir_WT_1_11_24.jpg",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4,
      reviews: 21,
    },
    {
      id: 5,
      category: "Clothing",
      type: "Women",
      name: "Product-5",
      price: 115.19,
      disprice: 95.99,
      image: "https://images.unsplash.com/photo-1642597611045-7bd6e09c4d2e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nzl8fGNsb3RoaW5nJTIwd2VBZnJlYw%3D%3D",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 6,
      category: "Clothing",
      type: "Women",
      name: "Product-6",
      price: 54.99,
      disprice: 45.99,
      image:       "https://images.unsplash.com/photo-1615125990940-590bb28a2cea?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d29tZW4lMjBjbG90aGVzJTIwJTIwcGhvdG9ncmFwaHl8ZW58MHwwfDB8fHww",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      rating: 5,
      reviews: 18,
    },
  
  {
    id: 7,
    category: "Clothing",
    type: "Women",
    name: "Product-7",
    price: 99.99,
    disprice: 64.99,
    image:
      "https://sassafras.in/cdn/shop/products/SFSWSH7464-5_1800x.jpg?v=1700582719",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 8,
    category: "Clothing",
    type: "Women",
    name: "Product-8",
    price : 109.99,
    disprice: 79.99,
    image:
      "https://thevishnu.in/cdn/shop/articles/blog1_vishnu_900x.png?v=1718008804",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 3,
    reviews: 80,
  },

  {
    id: 9,
    category: "Clothing",
    type: "Women",
    name: "Product-9",
    price: 149.99,
    disprice: 119.99,
    image:
      "https://cdn.shopify.com/s/files/1/0582/2270/6885/files/2_1ebdbb00-7c59-4a6d-ada0-54b29b15dea3.jpg?v=1632141942",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 4,
    reviews: 8,
  },

  {
    id: 10,
    category: "Clothing",
    type: "Women",
    name: "Product-10",
    price: 169.99,
    disprice: 129.99,
    image:
      "https://www.instyle.com/thmb/2vTd6ZZW5hRCu8Xv5-JxC_tvSWk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-2153285641-0a7d20bfbe7949a4bfea27ad075d175f.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    rating: 1,
    reviews: 1,
  },

  // --------------------------------------------------------------- Electronics ---------------------------------------------------------------
  {
    id: 1,
    category: "Electronics",
    type: "Tech",
    name: "Premium Wireless Headphones",
    disprice: 299.99,
    price: 359.99,  // 20% higher than disprice
    description: "High-quality wireless headphones with noise cancellation",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    stock: 10,
    rating: 4.5,
    reviews: 210,
},
{
    id: 2,
    category: "Electronics",
    type: "Tech",
    name: "4K Smart TV",
    disprice: 799.99,
    price: 959.99,  // 20% higher than disprice
    description: "55-inch 4K Ultra HD Smart LED TV with HDR",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
    stock: 5,
    rating: 4.8,
    reviews: 310,
},
{
    id: 3,
    category: "Electronics",
    type: "Tech",
    name: "Professional Camera",
    disprice: 1299.99,
    price: 1559.99,  // 20% higher than disprice
    description: "24.2MP Digital SLR Camera with 18-55mm Lens",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
    stock: 3,
    rating: 4.7,
    reviews: 180,
},
{
    id: 4,
    category: "Electronics",
    type: "Tech",
    name: "Smartphone X Pro",
    disprice: 999.99,
    price: 1199.99,  // 20% higher than disprice
    description: "Latest smartphone with AI camera and 5G support",
    image: "https://images.unsplash.com/photo-1596495577880-bb541be2895c",
    stock: 8,
    rating: 4.6,
    reviews: 250,
},
{
    id: 5,
    category: "Electronics",
    type: "Tech",
    name: "Laptop Ultra 15",
    disprice: 1499.99,
    price: 1799.99,  // 20% higher than disprice
    description: "Powerful laptop with 16GB RAM and 512GB SSD",
    image: "https://images.unsplash.com/photo-1571252480151-7e5f3248f8cc",
    stock: 4,
    rating: 4.7,
    reviews: 300,
},
{
    id: 6,
    category: "Electronics",
    type: "Tech",
    name: "Bluetooth Speaker 360",
    disprice: 149.99,
    price: 179.99,  // 20% higher than disprice
    description: "Portable speaker with 360-degree sound",
    image: "https://images.unsplash.com/photo-1574200777525-0b378dca7aeb",
    stock: 15,
    rating: 4.3,
    reviews: 120,
},
{
    id: 7,
    category: "Electronics",
    type: "Tech",
    name: "Smartwatch S1",
    disprice: 249.99,
    price: 299.99,  // 20% higher than disprice
    description: "Stylish smartwatch with fitness tracking features",
    image: "https://images.unsplash.com/photo-1597757413573-d680105b9a44",
    stock: 20,
    rating: 4.4,
    reviews: 180,
},
{
    id: 8,
    category: "Electronics",
    type: "Tech",
    name: "Noise Cancelling Earbuds",
    disprice: 129.99,
    price: 155.99,  // 20% higher than disprice
    description: "In-ear earbuds with noise cancellation",
    image: "https://images.unsplash.com/photo-1575121416802-2451b40b8f62",
    stock: 12,
    rating: 4.6,
    reviews: 95,
},
{
    id: 9,
    category: "Electronics",
    type: "Tech",
    name: "Drone 4K Pro",
    disprice: 599.99,
    price: 719.99,  // 20% higher than disprice
    description: "4K drone with high-definition video recording",
    image: "https://images.unsplash.com/photo-1563914551-8aeb6d2d2511",
    stock: 6,
    rating: 4.9,
    reviews: 430,
},
{
    id: 10,
    category: "Electronics",
    type: "Tech",
    name: "Gaming Console X",
    disprice: 499.99,
    price: 599.99,  // 20% higher than disprice
    description: "Next-gen gaming console with 4K gaming capabilities",
    image: "https://images.unsplash.com/photo-1561070894-b5f35b7d0f2d",
    stock: 7,
    rating: 4.8,
    reviews: 350,
},

  
    //--------------------------------------------------------------------- HOME APPLIANCES ---------------------------------------------------------------------
  
    {
      id: 1,
      name: "Crystal Chandelier",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 459.99,
      price: 551.99,  // 20% higher than disprice
      description: "Elegant crystal chandelier to illuminate your space.",
      image: "https://img.freepik.com/free-photo/contemporary-chandelier_1385-2783.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      rating: 4.9,
      reviews: 20,
  },
  {
      id: 2,
      name: "Samsung Refrigerator",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 799.99,
      price: 959.99,  // 20% higher than disprice
      description: "Spacious fridge with advanced cooling technology.",
      image: "https://img.freepik.com/free-vector/opened-wider-empty-refrigerator_1284-23309.jpg?t=st=1731690723~exp=1731694323~hmac=2ffedf0e23a4ff47b4d3228fa00caea5a5cef63baad474b28deb4ffdf3f06b5e&w=740",
      rating: 4.8,
      reviews: 1220,
  },
  {
      id: 3,
      name: "LG Washing Machine",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 599.99,
      price: 719.99,  // 20% higher than disprice
      description: "High-efficiency washing machine with smart features.",
      image: "https://img.freepik.com/free-vector/washing-machine-realistic-poster-with-quiet-quick-wash-symbols-illustration_1284-29131.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      rating: 4.7,
      reviews: 100,
  },
  {
      id: 4,
      name: "Microwave Oven",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 249.99,
      price: 299.99,  // 20% higher than disprice
      description: "Compact oven for efficient cooking and reheating.",
      image: "https://img.freepik.com/free-vector/microwave-oven-with-light-inside-isolated-white-background-kitchen-appliances_134830-658.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
      rating: 4.6,
      reviews: 50,
  },
  {
      id: 5,
      name: "Water Purifier",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 199.99,
      price: 239.99,  // 20% higher than disprice
      description: "Advanced purifier for clean and safe drinking water.",
      image: "https://cdn-jmlld.nitrocdn.com/qydppaFNcKMRjVLinmLFvQMpPBYfFFCk/assets/images/optimized/rev-465a996/www.aosmithindia.com/wp-content/themes/aosmith/assets/images/water_purification.jpg",
      rating: 4.8,
      reviews: 30,
  },
  {
      id: 6,
      name: "Non-Stick Dosa Pan",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 29.99,
      price: 35.99,  // 20% higher than disprice
      description: "Durable non-stick pan for perfect dosas every time.",
      image: "https://www.potsandpans.in/cdn/shop/products/Edgeless_Tawa_1_900x.jpg?v=1572514225",
      rating: 4.5,
      reviews: 840,
  },
  {
      id: 7,
      name: "Mixer Grinder",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 89.99,
      price: 107.99,  // 20% higher than disprice
      description: "Versatile mixer grinder for your everyday kitchen needs.",
      image: "https://shop.kamalastores.com/cdn/shop/products/81AKlOUHvq3L_1024x1024@2x.png?v=1633184935",
      rating: 4.7,
      reviews: 620,
  },
  {
      id: 8,
      name: "Wet Grinder",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 129.99,
      price: 155.99,  // 20% higher than disprice
      description: "Efficient grinder for smooth batters and pastes.",
      image: "https://cdn.moglix.com/p/AJN7oE6lQJmF8-xxlarge.jpg",
      rating: 4.6,
      reviews: 365,
  },
  {
      id: 9,
      name: "Kitchen Utensils Set",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 59.99,
      price: 71.99,  // 20% higher than disprice
      description: "Complete set of utensils for a modern kitchen.",
      image: "https://media.istockphoto.com/id/586162072/photo/various-kitchen-utensils.jpg?s=612x612&w=0&k=20&c=auwz9ZHqkG_UlKw5y-8UqvMLznA2PySQ_Jt3ameL1aU=",
      rating: 4.9,
      reviews: 190,
  },
  {
      id: 10,
      name: "Gas Stove",
      category: "HomeAppliances",
      type: "Appliances",
      disprice: 159.99,
      price: 191.99,  // 20% higher than disprice
      description: "Durable and efficient gas stove for your cooking needs.",
      image: "https://www.hitechappliances.net/image/cache/catalog/products/hob_4b_plus/1-421x523.jpg",
      rating: 4.8,
      reviews: 500,
  },
  
  // --------------------------------------------------------------- Shoes ---------------------------------------------------------------

  {
    id: 1,
    category: "Shoes",
    type: "Running",
    name: "Classic Running Shoes",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    alt: "Classic white and red running shoes",
    rating: 4.3,
    reviews: 150,
  },
  {
    id: 2,
    category: "Shoes",
    type: "Running",
    name: "Urban Sneakers",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    alt: "Modern urban style sneakers",
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 3,
    category: "Shoes",
    type: "Running",
    name: "Sport Elite",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570",
    alt: "Premium sports running shoes",
    rating: 4.8,
    reviews: 200,
  },
  {
    id: 4,
    category: "Shoes",
    type: "Running",
    name: "Comfort Walker",
    price: 99.99,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    alt: "Comfortable walking shoes",
    rating: 4.0,
    reviews: 85,
  },
  {
    id: 5,
    category: "Shoes",
    type: "Running",
    name: "Trail Runner Pro",
    price: 159.99,
    image: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2",
    alt: "Professional trail running shoes",
    rating: 4.6,
    reviews: 140,
  },
  {
    id: 6,
    category: "Shoes",
    type: "Running",
    name: "Lifestyle Series",
    price: 139.99,
    image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    alt: "Casual lifestyle sneakers",
    rating: 4.2,
    reviews: 95,
  },

  {
    id: 7,
    category: "Shoes",
    type: "Running",
    name: "Ultra Boost Runner",
    price: 199.99,
    image:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    alt: "High-performance running shoes with extra cushioning",
    rating: 4.7,
    reviews: 250,
  },
  {
    id: 8,
    category: "Shoes",
    type: "Running",
    name: "Puma Trail strip",
    price: 189.99,
    image:
      "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTQVMxIHT9EYjPLDV-b23vo1dU17wYqm-EOmgmOWcKY2aUetBbD4MGnvv4OGFfgnoh0Gum56OcYLRh1bVW6rqeWjz0rtzAVGCAVjqet3N3PJvjuOiWZGZ3zCw&usqp=CAE",
    alt: "Durable trail running shoes for rugged terrain",
    rating: 4.6,
    reviews: 180,
  },
  {
    id: 9,
    category: "Shoes",
    type: "Running",
    name: " Nike Air Max",
    price: 789.99,
    image:
      "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    alt: "Lightweight and breathable jogging shoes",
    rating: 4.2,
    reviews: 90,
  },
  {
    id: 10,
    category: "Shoes",
    type: "Running",
    name: "Nike D7000",
    price: 1799.99,
    image:
      "https://images.unsplash.com/photo-1537636568536-a2e00b44cb85?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTl8fFNwZWVkVHJhaWwlMjBYJTIwc2hvZXxlbnwwfHwwfHx8MA%3D%3D",
    alt: "Specialized sprinting shoes for athletes",
    rating: 4.8,
    reviews: 300,
  },

  //--------------------------------------------------------------------- TOYS ---------------------------------------------------------------------
  {
    id: 1,
    name: "Toy Story Set",
    category: "Toys",
    type: "All",
    price: 159.99,
    description: "A complete set of Toy Story characters for kids.",
    image:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRWg9L8BhasUi4nJyVGNRRifx4QaE--E5F22jCySl5JtWQEv0_6gb_uwfni3sV9_SyzC3Xk1LqKH28l8Edmgiv6YHhXcTjyH33ZyBDAP2v5AYahm2bi0pxM&usqp=CAE",
    popularity: 4.8,
  },
  {
    id: 2,
    name: "Lego AMG and G-Wagon",
    category: "Toys",
    type: "All",
    price: 99.99,
    description: "Creative Lego blocks for AMG and G-wagon play.",
    image:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ11zX7x7rHahljN__cu8AG2_6A4_rIhYPCYQWYX2nFmHlD_wcTDUAo_9eV_NpsdQAZbjR0nEsbKtw-Flrb9iPZPjR0H8rbBw1GYqUnFt8G&usqp=CAE",
    popularity: 4.9,
  },
  {
    id: 3,
    name: "Remote Control Car",
    category: "Toys",
    type: "All",
    price: 49.99,
    description: "High-speed remote control car with rechargeable battery.",
    image:
      "https://img.freepik.com/premium-photo/remote-control-car-with-rechargeable-battery_872941-2220.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    popularity: 4.7,
  },
  {
    id: 4,
    name: "Barbie Dollhouse",
    category: "Toys",
    type: "All",
    price: 129.99,
    description: "A luxurious dollhouse with furniture for Barbie dolls.",
    image:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQS-juHGNXnlA_vUVqCnQ9McttfAZTGX6mDRAR3bmnVRh2VtcGxpbK7gkhVHr0s5lcgTVoVsk4VtZPkfYCtyMETlFRI_uyfJt0L75Duv0mT&usqp=CAE",
    popularity: 4.8,
  },
  {
    id: 5,
    name: "Stuffed Teddy Bear",
    category: "Toys",
    type: "All",
    price: 29.99,
    description: "Soft and cuddly teddy bear for endless hugs.",
    image:
      "https://img.freepik.com/free-photo/cute-teddy-bear-indoors-still-life_23-2151083636.jpg?uid=R167280267&ga=GA1.1.1202719033.1728482629&semt=ais_hybrid",
    popularity: 4.9,
  },
  {
    id: 6,
    name: "Puzzle Set",
    category: "Toys",
    type: "All",
    price: 19.99,
    description: "Engaging puzzle set to challenge young minds.",
    image:
      "https://rukminim2.flixcart.com/image/720/864/kst9gnk0/role-play-toy/q/n/i/kids-number-puzzles-mini-size-play-puzzle-numbers-set-toy-kids-original-imag6bfkdjhyh9wx.jpeg?q=60&crop=false",
    popularity: 4.6,
  },
  {
    id: 7,
    name: "Rubik's original",
    category: "Toys",
    type: "All",
    price: 49.99,
    description: "A Puzzle cube of 3x3 side ",
    image:
      "https:////rukminim2.flixcart.com/image/850/1000/kpft18w0/puzzle/o/m/k/1-high-speed-rubik-s-cube-smooth-magic-puzzle-cube-brainteaser-original-imag3zmgzfawsvj8.jpeg?q=90&crop=false",
    popularity: 4.7,
  },
  {
    id: 8,
    name: "Play Kitchen Set",
    category: "Toys",
    type: "All",
    price: 79.99,
    description: "Miniature kitchen set for fun cooking role-play.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTYEc4R0IQgPoZNw8Xg7sS-h6_DaQpdFWIMOWUuOS9SsKgRl2NvkPpEmgCNPytICzcCezbyi8BijxGSOachzQmF7acOOVjlA3RXfxWuv81lbN7VFvW5vziZ&usqp=CAE",
    popularity: 4.8,
  },
  {
    id: 9,
    name: "Toy Train Set",
    category: "Toys",
    type: "All",
    price: 89.99,
    description: "Electric toy train set with tracks and accessories.",
    image:
      "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQV5IiBaZ6-H55zK08KsdNvVYnWv_ca-0Ap1zOx-IVRwfrxrXXjOiXeUo1jlahZ2CMiyYIdQHQIhTMYiFr-jXEqxWbvW994QyxKXMJzK3US4E8UEDQ6NMsD&usqp=CAE",
    popularity: 4.6,
  },
  {
    id: 10,
    name: "Kids Art Supplies",
    category: "Toys",
    type: "All",
    price: 39.99,
    description: "Complete set of art supplies to inspire creativity.",
    image:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSqaChfZ-_Z6Bf5_F9_l5yBGsP0OHNzvpChj4clsiWTo2EIRcGlH9VR7EggEanCUlAgPZ3Bw-ucWF36HdSMb-fpNth4rHeaTEpPWLKleSw&usqp=CAE",
    popularity: 4.7,
    reviews: 100,
  },

  // -------------------------------------------------------------- COSMETICS ----------------------------------------------------------------------------------------------

  {
    id: -1,
    name: "Matte Lipstick Set",
    category: "Cosmetics",
    type: "All",
    price: 29.99,
    description: "Long-lasting matte lipstick set with vibrant colors.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTqm_mGWcT-lgHR86j6szNjlXeCjsUwvLF3eOGPzm8isISFS0vWZXEo7s0RVOVlOF7KekhxeywokyxusVmt_7qb2oVNnQrt_1KLrx03iXECGZbOaewFlnfP&usqp=CAE",
    popularity: 4.8,
  },
  {
    id: -2,
    name: "Hydrating Face Cream",
    category: "Cosmetics",
    type: "All",
    price: 24.99,
    description: "Deeply moisturizing face cream for glowing skin.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRC1hkoxDFBk22tDIlAcXsXhNO4pg959h6goDK0xJ9S5I-jR6ooKp2R2MMzHBf4PZUOJeKe_76SvcWppuj_d54yzEOdugxpjoZKSiFrbo1H&usqp=CAE",
    popularity: 4.7,
  },
  {
    id: -3,
    name: "Waterproof Mascara",
    category: "Cosmetics",
    type: "All",
    price: 19.99,
    description: "Smudge-proof and waterproof mascara for dramatic lashes.",
    image:
      "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSZ4bMNVLe6hqr4yulUVpavG2vKTLxWlruHhtgTqgy6CphqhAO5rFLNDwahMxtqmYmLV-v9EjuQl3V92jxoakCEshlE47IhOXbgEnACou8cpQ7iHzQNX693&usqp=CAE",
    popularity: 4.9,
  },
  {
    id: -4,
    name: "Vitamin C Serum",
    category: "Cosmetics",
    type: "All",
    price: 39.99,
    description: "Brightening serum with vitamin C and hyaluronic acid.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR0r3GteRu6ds8deytla3wkbtKeHQR2hzhcMj1xgM_quCZa0wrhJqMuo8NR6bc4dQUv0SULWO7TBWwhI6oO1Z4oDt9VRJq07C5SD1WwrHlbjo0EeYSz94-Z-w&usqp=CAE",
    popularity: 4.8,
  },
  {
    id: -5,
    name: "Eyeshadow Palette",
    category: "Cosmetics",
    type: "All",
    price: 49.99,
    description: "Palette with 16 pigmented shades for every occasion.",
    image:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSPjm8zxOtGUzAknJbmzXplsJBPJx4ens_EEeQBTtSkNESxxBlfpTFDKGI1HJ-g-RU4jKONkwF_RUzWIdQp_tc2IAeBr6RwQYM4h_mg2JppAUy67HrqutL7&usqp=CAE",
    popularity: 4.6,
  },
  {
    id: -6,
    name: "Nail Polish Set",
    category: "Cosmetics",
    type: "All",
    price: 15.99,
    description: "Collection of quick-drying nail polishes in trendy colors.",
    image:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQSWv1Ac9HUE908Hh24jpdTTwXabziaN717Dc254PEUszJYWk7sFu73T_P0xDrzI6Rww_jvZaCSvg4WwvCsFb7jxpaH5SWVQl19GB3tbMzdReg8X_Kri465&usqp=CAE",
    popularity: 4.7,
  },
  {
    id: -7,
    name: "Liquid Foundation",
    category: "Cosmetics",
    type: "All",
    price: 34.99,
    description: "Lightweight foundation for a flawless base.",
    image:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQsvpi9ERCVnucmhXN4MksKg-TDesznPFW1zfE8NUTERu5j_5irTMbsgvExc9juDoqCuAVJVIWJkuTA0T3Ld89vP0Jf7wmQViEQ2BINUaqbMuElNSTmUXhmh58&usqp=CAE",
    popularity: 4.8,
  },
  {
    id: -8,
    name: "Charcoal Face Mask",
    category: "Cosmetics",
    type: "All",
    price: 19.99,
    description: "Detoxifying face mask with activated charcoal.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS1wMjupLtcwJhiFnRXB-aPWYtE7UVWl1MACkM44Yu4FNPPx_P-HUpsK8UM70Veu3ZnDZIbssaYyFTkCCLdaQ_FaQqNc1bEd3kc80XtP8wNEEouIsTIxtxN&usqp=CAE",
    popularity: 4.5,
  },
  {
    id: -9,
    name: "Makeup Brushes Set",
    category: "Cosmetics",
    type: "All",
    price: 29.99,
    description: "Professional brush set for seamless makeup application.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTrxu7iJnzpbX1JxzK5zb3LMHzeXro8R2E6-626KQ2izboch2hRoNouSn8smXAh2JvGpEbh8W_Kd7eS4VkfZFa_3f1to-wGXPK7kO7uD1avv8YPxMqY_uMU&usqp=CAE",
    popularity: 4.9,
  },
  {
    id: -10,
    name: "Sunscreen SPF 50",
    category: "Cosmetics",
    type: "All",
    price: 25.99,
    description: "Broad-spectrum sunscreen with SPF 50 for sun protection.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSIN90_RNvojoQAm3EHsCA7djizl6T3U5DWs9UlWn1E-rLdqBxXlUg0fokSPtUKjmU_TkD76AKXp5fec6AjwAt5LEr19HJbi-HDUrAmmmbmfMCzu26hBiIX&usqp=CAE",
    popularity: 4.8,
  },

  // -------------------------------------------------------------- TOOLS AND EQUIPMENTS ------------------------------------------------------------------------------------------------

  {
    id: 0 - 1,
    name: "Cordless Drill",
    category: "Tools",
    type: "Equipments",
    price: 89.99,
    description: "High-performance cordless drill with rechargeable battery.",
    image:
      "https://technocart.com/cdn/shop/products/bosch-cordless-drill-driver-gsr-180-li-00.jpg?v=1667474112",
    popularity: 4.8,
  },

  {
    id: 0 - 2,
    name: "Adjustable Wrench",
    category: "Tools",
    type: "Equipments",
    price: 14.99,
    description: "Durable adjustable wrench for various bolt sizes.",
    image: "https://m.media-amazon.com/images/I/51IwMYU+vaL._AC_SL1001_.jpg",
    popularity: 4.7,
  },
  {
    id: 0 - 3,
    name: "Circular Saw",
    category: "Tools",
    type: "Equipments",
    price: 129.99,
    description: "Efficient circular saw for precise wood and metal cutting.",
    image:
      "https://industrylots.com/media/catalog/product/cache/d20d95e66dace23eb5c8a3e2470a038f/i/m/img-20220412-wa0002.jpg",
    popularity: 4.8,
  },
  {
    id: 0 - 4,
    name: " Measuring Tape",
    category: "Tools",
    type: "Equipments",
    price: 9.99,
    description: "Retractable tape measure with a 25-foot reach.",
    image: "https://cdn.moglix.com/p/AbEHiNM8w82XU-xxlarge.jpg",
    popularity: 4.6,
  },
  {
    id: 0 - 5,
    name: "Multi-Bit Screwdriver",
    category: "Tools",
    type: "Equipments",
    price: 19.99,
    description: "Ergonomic screwdriver with interchangeable bits.",
    image: "https://m.media-amazon.com/images/I/61GyKdFTuHL.jpg",
    popularity: 4.7,
  },
  {
    id: 0 - 6,
    name: "Toolbox Organizer",
    category: "Tools",
    type: "Equipments",
    price: 34.99,
    description: "Compact toolbox for organizing and storing tools.",
    image:
      "https://images.klgsys.com/pim/original/49/10177449/c1d1f8eb-cd67-4dcf-902a-7345103337bb_10177449.jpg",
    popularity: 4.9,
  },
  {
    id: 0 - 7,
    name: "Electric Sander",
    category: "Tools",
    type: "Equipments",
    price: 49.99,
    description: "Smooth finish electric sander for woodworking projects.",
    image:
      "https://d3ciiv7axt9x6p.cloudfront.net/category/original/652667527c3ae_ori.jpg",
    popularity: 4.5,
  },
  {
    id: 0 - 8,
    name: "Hammer",
    category: "Tools",
    type: "Equipments",
    price: 12.99,
    description: "Heavy-duty hammer for construction and DIY tasks.",
    image:
      "https://media.istockphoto.com/id/147062650/photo/hammer.jpg?s=612x612&w=0&k=20&c=LijPyNhxQhh2PREHEZ8xaU5qgE3YcVEY34btzouQGbs=",
    popularity: 4.7,
  },
  {
    id: 0 - 9,
    name: "Work Gloves",
    category: "Tools",
    type: "Equipments",
    price: 9.99,
    description: "Durable and comfortable gloves for protection.",
    image:
      "https://m.media-amazon.com/images/I/51UK0LtA86L._AC_UF894,1000_QL80_.jpg",
    popularity: 4.8,
  },
  {
    id: 0 - 10,
    name: "Euro Ladder",
    category: "Tools",
    type: "Equipments",
    price: 74.99,
    description: "Sturdy folding ladder for household and professional use.",
    image:
      "https://5.imimg.com/data5/RN/QR/IS/SELLER-6652341/euro-ecox-series-aluminium-step-ladder-with-tool-tray-ultra-light-aerospace-aluminium-500x500.jpg",
    popularity: 4.6,
  },

  // ----------------------------------------------------------------- STATIONERY ITEMS -------------------------------------------------------------------------------

  {
    id: 11,
    name: "Classic Ballpoint Pen",
    category: "Stationery",
    type: "All",
    price: 6.59, // Increased by 10%
    disprice: 5.93, // 10% lower than price
    description: "A set of 10 smooth and reliable ballpoint pens.",
    image:
      "https://www.buzzstore.in/ecommerce/upload/images/edit/parker-classic-matte-metal-ball-pen-58-2024-07.jpg",
    rating: 4.8,
    reviews: 120,
  },
  {
    id: 12,
    name: "Hardcover Notebook",
    category: "Stationery",
    type: "All",
    price: 10.99, // Increased by 10%
    disprice: 9.89, // 10% lower than price
    description: "Durable notebook with ruled pages, perfect for journaling.",
    image: "https://cdn.moglix.com/p/atEZfJgyyqn37-xxlarge.jpg",
    rating: 4.7,
    reviews: 95,
  },
  {
    id: 13,
    name: "Colorful Sticky Notes",
    category: "Stationery",
    type: "All",
    price: 5.49, // Increased by 10%
    disprice: 4.94, // 10% lower than price
    description:
      "Bright and colorful sticky notes for reminders and bookmarks.",
    image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSeGzO8m8LTGlVaOy1qqj_ewsx2XhBpXSW1nh139lUy3j7pUgOWEEypE3SzZyI9sbOLaJ6e-CHmVJhdnfQHdILtOPfw-SVbRMgOWLbpSmuKRDKyM7UnOukf2g&usqp=CAE",
    rating: 4.6,
    reviews: 80,
  },
  {
    id: 14,
    name: "Mechanical Pencils Set",
    category: "Stationery",
    type: "All",
    price: 8.79, // Increased by 10%
    disprice: 7.91, // 10% lower than price
    description: "Pack of 5 refillable mechanical pencils with 0.5mm leads.",
    image: "https://source.unsplash.com/400x400/?pencil",
    rating: 4.7,
    reviews: 110,
  },
  {
    id: 15,
    name: "Highlighter Pack",
    category: "Stationery",
    type: "All",
    price: 7.69, // Increased by 10%
    disprice: 6.92, // 10% lower than price
    description: "Set of 6 fluorescent highlighters for study and office work.",
    image: "https://source.unsplash.com/400x400/?highlighter",
    rating: 4.9,
    reviews: 150,
  },
  {
    id: 16,
    name: "Desk Organizer",
    category: "Stationery",
    type: "All",
    price: 14.29, // Increased by 10%
    disprice: 12.86, // 10% lower than price
    description: "Compact desk organizer with multiple compartments for tools.",
    image: "https://source.unsplash.com/400x400/?desk-organizer",
    rating: 4.8,
    reviews: 90,
  },
  {
    id: 17,
    name: "Erasable Gel Pens",
    category: "Stationery",
    type: "All",
    price: 14.29, // Increased by 10%
    disprice: 12.86, // 10% lower than price
    description:
      "Set of 3 gel pens with erasable ink for mistake-free writing.",
    image: "https://source.unsplash.com/400x400/?erasable-pen",
    rating: 4.6,
    reviews: 65,
  },
  {
    id: 18,
    name: "Stapler with Staples",
    category: "Stationery",
    type: "All",
    price: 7.14, // Increased by 10%
    disprice: 6.43, // 10% lower than price
    description: "Compact stapler with 500 staples included for easy use.",
    image: "https://source.unsplash.com/400x400/?stapler",
    rating: 4.7,
    reviews: 105,
  },
  {
    id: 19,
    name: "Ruler and Protractor Set",
    category: "Stationery",
    type: "All",
    price: 4.39, // Increased by 10%
    disprice: 3.95, // 10% lower than price
    description: "Essential tools for precision and geometry tasks.",
    image: "https://source.unsplash.com/400x400/?ruler",
    rating: 4.6,
    reviews: 60,
  },
  {
    id: 20,
    name: "Artistic Sketch Pad",
    category: "Stationery",
    type: "All",
    price: 16.49, // Increased by 10%
    disprice: 14.84, // 10% lower than price
    description: "High-quality sketch pad with textured pages for drawing.",
    image: "https://source.unsplash.com/400x400/?sketchbook",
    rating: 4.9,
    reviews: 200,
  },

  // --------------------------------------------------------------- HomeDecor ---------------------------------------------------------------
  {
    id: 1,
    category: "HomeDecor",
    type: "Decor",
    name: "Modern Table Lamp",
    price: 129.99,
    description: "Elegant table lamp with adjustable brightness",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15",
    popularity: 4.5,
    rating: 4.4,
    reviews: 90,
  },
  {
    id: 2,
    category: "HomeDecor",
    type: "Decor",
    name: "Velvet Accent Chair",
    price: 299.99,
    description: "Comfortable accent chair with premium velvet upholstery",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c",
    popularity: 4.8,
    rating: 4.8,
    reviews: 150,
  },
  {
    id: 3,
    category: "HomeDecor",
    type: "Decor",
    name: "Decorative Wall Mirror",
    price: 89.99,
    description: "Round wall mirror with golden frame",
    image:
      "https://shopps.in/wp-content/uploads/2022/07/designer-mirror-frame-1000x1000-1.webp",
    popularity: 4.2,
    rating: 4.3,
    reviews: 70,
  },
  {
    id: 4,
    category: "HomeDecor",
    type: "Decor",
    name: "Pendant Light Fixture",
    price: 159.99,
    description: "Modern pendant light with metal finish",
    image: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f",
    popularity: 4.6,
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 5,
    category: "HomeDecor",
    type: "Decor",
    name: "Leather Sofa",
    price: 899.99,
    description: "Premium leather sofa with modern design",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
    popularity: 4.9,
    rating: 4.9,
    reviews: 200,
  },
  {
    id: 6,
    category: "HomeDecor",
    type: "Decor",
    name: "Ceramic Vase Set",
    price: 79.99,
    description: "Set of 3 decorative ceramic vases",
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d",
    popularity: 4.3,
    rating: 4.2,
    reviews: 65,
  },
  {
    id: 7,
    category: "HomeDecor",
    type: "Decor",
    name: "Floor Lamp",
    price: 199.99,
    description: "Contemporary floor lamp with reading light",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c",
    popularity: 4.7,
    rating: 4.6,
    reviews: 110,
  },
  {
    id: 8,
    category: "HomeDecor",
    type: "Decor",
    name: "Dining Table Set",
    price: 699.99,
    description: "Modern dining table with 6 chairs",
    image: "https://images.unsplash.com/photo-1617806118233-18e1de247200",
    popularity: 4.8,
    rating: 4.9,
    reviews: 170,
  },
  {
    id: 9,
    category: "HomeDecor",
    type: "Decor",
    name: "Wall Clock",
    price: 49.99,
    description: "Minimalist wall clock with wooden frame",
    image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c",
    popularity: 4.4,
    rating: 4.3,
    reviews: 85,
  },
  {
    id: 10,
    category: "HomeDecor",
    type: "Decor",
    name: "Crystal Chandelier",
    price: 459.99,
    description: "Luxurious crystal chandelier for dining room",
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
    popularity: 4.9,
    rating: 4.9,
    reviews: 220,
  },

  // ----------------------------------------------------------------- BOOKS -------------------------------------------------------------------------------

  {
    id: 21,
    name: "The Great Gatsby",
    category: "Books",
    type: "All",
    price: 14.99,
    description:
      "A classic novel by F. Scott Fitzgerald exploring themes of wealth and ambition.",
    image: "https://source.unsplash.com/400x400/?book",
    popularity: 4.9,
  },
  {
    id: 22,
    name: "Sapiens: A Brief History of Humankind",
    category: "Books",
    type: "All",
    price: 19.99,
    description:
      "Yuval Noah Harari's exploration of humanity's history and evolution.",
    image: "https://source.unsplash.com/400x400/?non-fiction-book",
    popularity: 4.8,
  },
  {
    id: 23,
    name: "The Catcher in the Rye",
    category: "Books",
    type: "All",
    price: 12.99,
    description:
      "J.D. Salinger's iconic story of teenage rebellion and identity.",
    image: "https://source.unsplash.com/400x400/?novel",
    popularity: 4.7,
  },
  {
    id: 24,
    name: "Atomic Habits",
    category: "Books",
    type: "All",
    price: 16.99,
    description:
      "James Clear's guide to building good habits and breaking bad ones.",
    image: "https://source.unsplash.com/400x400/?self-help-book",
    popularity: 4.8,
  },
  {
    id: 25,
    name: "1984",
    category: "Books",
    type: "All",
    price: 15.99,
    description:
      "George Orwell's dystopian novel about a totalitarian society.",
    image: "https://source.unsplash.com/400x400/?1984-book",
    popularity: 4.9,
  },
  {
    id: 26,
    name: "Becoming",
    category: "Books",
    type: "All",
    price: 18.99,
    description: "Michelle Obama's inspiring memoir about her life and career.",
    image: "https://source.unsplash.com/400x400/?biography-book",
    popularity: 4.8,
  },
  {
    id: 27,
    name: "The Alchemist",
    category: "Books",
    type: "All",
    price: 13.99,
    description:
      "Paulo Coelho's tale of self-discovery and pursuing one's dreams.",
    image: "https://source.unsplash.com/400x400/?fiction-book",
    popularity: 4.7,
  },
  {
    id: 28,
    name: "Educated",
    category: "Books",
    type: "All",
    price: 17.99,
    description:
      "Tara Westover's memoir of overcoming a challenging childhood through education.",
    image: "https://source.unsplash.com/400x400/?memoir-book",
    popularity: 4.9,
  },
  {
    id: 29,
    name: "Harry Potter and the Sorcerer's Stone",
    category: "Books",
    type: "All",
    price: 20.99,
    description:
      "J.K. Rowling's magical story of Harry Potter's first year at Hogwarts.",
    image: "https://source.unsplash.com/400x400/?fantasy-book",
    popularity: 4.9,
  },
  {
    id: 30,
    name: "The Subtle Art of Not Giving a F*ck",
    category: "Books",
    type: "All",
    price: 15.99,
    description:
      "Mark Manson's counterintuitive approach to living a good life.",
    image: "https://source.unsplash.com/400x400/?motivational-book",
    popularity: 4.6,
  },
];
